export const ROUTES = {
  INDEX: "/",
  ANIMATIONS: {
    BASICS: {
      INDEX: "/animations/basics",
      TRANSLATE: "/animations/basics/translate",
      OPACITY: "/animations/basics/opacity",
      SCALE_ROTATE: "/animations/basics/scale-rotate",
      MULTIPLE_TRANSFORMS: "/animations/basics/multiple-transforms",
    },
    TIMING: {
      INDEX: "/animations/timing",
      BASIC_TIMING: "/animations/timing/basic-timing",
      EASING: "/animations/timing/easing",
      SEQUENCE: "/animations/timing/sequence",
      DELAY_REPEAT: "/animations/timing/delay-repeat",
      INTERRUPTION: "/animations/timing/interruption",
    },
    SPRING: {
      INDEX: "/animations/spring",
      BASICS: "/animations/spring/basics",
      CONFIGS: "/animations/spring/configs",
      OVERSHOOT: "/animations/spring/overshoot",
      GESTURE: "/animations/spring/gesture",
      CHAIN: "/animations/spring/chain",
      COMPARISON: "/animations/spring/comparison",
    },
    DERIVED: {
      INDEX: "/animations/derived",
      BASICS: "/animations/derived/basics",
      OPACITY: "/animations/derived/opacity",
      CLAMP: "/animations/derived/clamp",
      CHAIN: "/animations/derived/chain",
      GESTURE: "/animations/derived/gesture",
    },
    INTERPOLATE: {
      INDEX: "/animations/interpolate",
      BASICS: "/animations/interpolate/basics",
      CLAMP: "/animations/interpolate/clamp",
      MULTI_STEP: "/animations/interpolate/multi-step",
      SCROLL: "/animations/interpolate/scroll",
      COLOR: "/animations/interpolate/color",
    },
    GESTURES: {
      INDEX: "/animations/gestures",
      PAN_GESTURE_BASICS: "/animations/gestures/pan-gesture-basics",
      DRAG_WITH_BOUNDARIES: "/animations/gestures/drag-with-boundaries",
      SWIPE_TO_DISMISS: "/animations/gestures/swipe-to-dismiss",
      GESTURE_WITH_SPRING: "/animations/gestures/gesture-with-spring",
      GESTURE_SNAP_POINTS: "/animations/gestures/gesture-snap-points",
      GESTURE_VS_STATE: "/animations/gestures/gesture-vs-state",
    },
    PATTERNS: {
      INDEX: "/animations/patterns",
      TOGGLE: "/animations/patterns/toggle",
      PROGRESS_DRIVEN: "/animations/patterns/progress-driven",
      GESTURE_DRIVEN: "/animations/patterns/gesture-driven",
      STATE_MACHINE: "/animations/patterns/state-machine",
      ANIMATION_HOOK: "/animations/patterns/animation-hook",
      COMPOUND_ANIMATION: "/animations/patterns/compound-animation",
    },
    SCROLL: {
      INDEX: "/animations/scroll",
      BASICS: "/animations/scroll/basics",
    },
  },
};
